name: Build

on:
  push:
    tags:
      - 'current'

permissions:
  contents: write

jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'app.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'EsoAddOnsUpdater-Windows'
      - name: Write version
        run: |
          echo ${{ github.sha }} > dist/version.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./dist/app.exe
            ./dist/version.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pyinstaller-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'app.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'EsoAddOnsUpdater-Linux'
      - name: Write version
        run: |
          echo ${{ github.sha }} > dist/version.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./dist/app
            ./dist/version.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
